# Generated by Django 4.2 on 2023-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_request_adress_request_theme_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время запроса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='text',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание статуса'),
        ),
    ]
